### ISSUE TITLE
Unterminated comment

### ISSUE THREAD

**Issue by litvinok** [Ocramius/ProxyManager#179] opened 2014-10-02 12:46 UTC
I've got php warning after update `zendframework/zend-code` to  2.3.2 or greater. Stack trace is below:

```
PHP Warning:  Unterminated comment starting line 24 in ~/project/vendor/zendframework/zend-code/Zend/Code/Reflection/MethodReflection.php on line 230
PHP Stack trace:
PHP   1. {main}() ~/project/app/console:0
PHP   2. Symfony\Component\Console\Application->run() ~/project/app/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() ~/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() ~/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() ~/project/app/bootstrap.php.cache:2304
PHP   6. Symfony\Component\HttpKernel\Kernel->dumpContainer() ~/project/app/bootstrap.php.cache:2526
PHP   7. Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() ~/project/app/bootstrap.php.cache:2609
PHP   8. Symfony\Component\DependencyInjection\Dumper\PhpDumper->addProxyClasses() ~/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:120
PHP   9. Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyCode() ~/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:205
PHP  10. ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() ~/project/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php:98
PHP  11. ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor::generateMethod() ~/project/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:83
PHP  12. ProxyManager\Generator\MethodGenerator::fromReflection() ~/project/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php:46
PHP  13. Zend\Code\Reflection\MethodReflection->getContents() ~/project/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/MethodGenerator.php:64
PHP  14. Zend\Code\Reflection\MethodReflection->extractMethodContents() ~/project/vendor/zendframework/zend-code/Zend/Code/Reflection/MethodReflection.php:193
PHP  15. token_get_all() ~/project/vendor/zendframework/zend-code/Zend/Code/Reflection/MethodReflection.php:230
PHP Warning:  Unterminated comment starting line 24 in ~/project/vendor/zendframework/zend-code/Zend/Code/Reflection/MethodReflection.php on line 230
PHP Stack trace:
PHP   1. {main}() ~/project/app/console:0
PHP   2. Symfony\Component\Console\Application->run() ~/project/app/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() ~/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() ~/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() ~/project/app/bootstrap.php.cache:2304
PHP   6. Symfony\Component\HttpKernel\Kernel->dumpContainer() ~/project/app/bootstrap.php.cache:2526
PHP   7. Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() ~/project/app/bootstrap.php.cache:2609
PHP   8. Symfony\Component\DependencyInjection\Dumper\PhpDumper->addProxyClasses() ~/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:120
PHP   9. Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyCode() ~/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:205
PHP  10. ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() ~/project/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php:98
PHP  11. ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor::generateMethod() ~/project/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:83
PHP  12. ProxyManager\Generator\MethodGenerator::fromReflection() ~/project/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php:46
PHP  13. Zend\Code\Reflection\MethodReflection->getBody() ~/project/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/MethodGenerator.php:80
PHP  14. Zend\Code\Reflection\MethodReflection->extractMethodContents() ~/project/vendor/zendframework/zend-code/Zend/Code/Reflection/MethodReflection.php:205
PHP  15. token_get_all() ~/project/vendor/zendframework/zend-code/Zend/Code/Reflection/MethodReflection.php:230
```

**Comment by DHager** [comment] 2015-04-30 17:39
Just encountered this problem in the wild... It turns out this thread is the only google-result for "extractMethodContents traits". In my case I'm using traits on an object which is being lazy-loaded by PHP-DI, which uses ProxyManager.

Here's hoping the PHP bug is fixed.

**Comment by Ocramius** [comment] 2015-04-30 17:45
Can anyone provide a test case for this one?

**Comment by DHager** [comment] 2015-04-30 17:59
You mean, just so that you find out when/if the underlying core PHP bug is finally fixed?

Or to guide some sort of workaround within ProxyManager?

**Comment by Ocramius** [comment] 2015-04-30 18:04
Just a test case exposing the bug in ProxyManager would allow searching for a solution first, regardless of how correct it may be.

**Comment by DHager** [comment] 2015-04-30 21:59
OK, I wasn't able to reproduce the same issue inside the tests for ProxyManager, and I think it's because composer is pulling in `zendframework/zend-code` version 2.4.0, which seems to have fixed (or worked around) the issue compared to 2.3.4 where I was having problems. 

Specifically, `MethodReflection::extractMethodContents()` uses a slightly different tactic for determining which file contains the source-code for methods,  which changed in [this commit](https://github.com/zendframework/Component_ZendCode/commit/cfd5951ff4348e4430850560416c7ddb755f95d3).

In version 2.3.4, the program was failing while inspecting a method that came from the trait, because it was searching inside the main-class-file, albeit with the correct line offsets for the trait-file. It was finding the filename with `$this->getDeclaringClass()->getFileName()` .

In 2.4.0, it is now pulling from the correct file, with `$this->getFileName()` .

**Comment by Ocramius** [comment] 2018-08-05 15:16
Closing here: `zendframework/zend-code` is phasing out all code parsing facilities, so this should be gone by then. Besides that, the bug is in the dependency, not here.

**Closed by Ocramius** 2018-08-05 15:16 UTC
Labels: bug
