### ISSUE TITLE
Cloning lazy instantiated objects

### ISSUE THREAD

**Issue by theofidry** [Ocramius/ProxyManager#332] opened 2016-08-29 16:18 UTC

**Comment by Ocramius** [comment] 2016-08-29 16:34
Duplicate of #333

**Closed by Ocramius** 2016-08-29 16:34 UTC

**Comment by theofidry** [comment] 2016-08-29 16:37
ah... sorry about that

**Comment by Ocramius** [comment] 2016-08-29 16:47
https://www.youtube.com/watch?v=4QWfrxYt9DQ
