### ISSUE TITLE
Zend-code abandoned/moved

### ISSUE THREAD

**Issue by onokje** [Ocramius/ProxyManager#551] opened 2020-01-03 20:25 UTC
Warnings on install:

Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.

Looks like they just moved the repo's.

**Comment by Ocramius** [comment] 2020-01-03 20:26
Duplicate of #546

**Closed by Ocramius** 2020-01-03 20:26 UTC
