### ISSUE TITLE
ProxyManager\Configuration::setGeneratorStrategy() must be an instance of ProxyManager\void, none returned

### ISSUE THREAD

**Issue by claborier** [Ocramius/ProxyManager#368] opened 2017-03-31 12:47 UTC
Hi ! 

I have a `Symfony3` project with a backend based on [easyAdminBundle](https://github.com/javiereguiluz/EasyAdminBundle) 

EasyAdmin give some documentation to integrate [VichUploader](https://github.com/javiereguiluz/EasyAdminBundle/blob/master/Resources/doc/tutorials/upload-files-and-images.md) to manage file upload.

VichUploader require ocramius/proxy-manager v2.0 : 
`vich/uploader-bundle  1.5.2   requires  ocramius/proxy-manager (^2.0) `

Since I've installed it, I often face to the same error related to proxy-manager : 

`FatalThrowableError in Configuration.php line 124: Type error: Return value of ProxyManager\Configuration::setGeneratorStrategy() must be an instance of ProxyManager\void, none returned`

And the stack trace : 
```
1.    in Configuration.php line 124
2.    at Configuration->setGeneratorStrategy(object(EvaluatingGeneratorStrategy)) in RuntimeInstantiator.php line 37
3.    at RuntimeInstantiator->__construct() in Kernel.php line 628
4.    at Kernel->getContainerBuilder() in Kernel.php line 577
5.    at Kernel->buildContainer() in Kernel.php line 486
6.    at Kernel->initializeContainer() in Kernel.php line 116
7.    at Kernel->boot() in Kernel.php line 165
8.    at Kernel->handle(object(Request)) in app_dev.php line 28
```

I'm currently working in `dev env` , and It happens every time I edit on of my `config.yml` files. 
I can temporally fix the error by clearing the cache : 
`php bin/console cache:clear`

Is everyone else facing the issue ? 

Thanks !

**Comment by Ocramius** [comment] 2017-03-31 12:48
Duplicate of #362

**Closed by Ocramius** 2017-03-31 12:48 UTC

**Comment by claborier** [comment] 2017-03-31 12:50
Sorry I miss that one ;)
