### ISSUE TITLE
Double call the parent method, when the name of the method matches the class name

### ISSUE THREAD

**Issue by DaGhostman** [Ocramius/ProxyManager#338] opened 2016-09-28 19:27 UTC
I was playing around with proxies and suddenly encountered a strange issue, reproduced by the code below:

```
$proxy = new \ProxyManager\Factory\AccessInterceptorScopeLocalizerFactory();

class Foo
{
    public function foo()
    {
        echo '2';
    }
}
$foo = $proxy->createProxy(
    new Foo(),
    ['foo' => function() {echo '1';}],
    ['foo' => function () { echo '3';}]
);

$foo->foo();
```

Expected output: `123`
Actual output: `22`
Tested on: PHP 7.0.11
Affected Package Versions: `^1,0`, `^2.0` 

This is definitely not an expected behaviour, since it is not documented anywhere. I personally don't see it intended behaviour, am I wrong?

**Comment by Ocramius** [comment] 2016-09-28 19:31
That is indeed NOT the intended behavior. Does it do the same when running https://github.com/Ocramius/ProxyManager/blob/b542cc4167215a778357412d307a87f531051fd8/examples/access-interceptor-scope-localizer.php ?

**Comment by Ocramius** [comment] 2016-09-28 19:31
Oh, wait... turn on error reporting. Your `Foo::foo()` may be considered a constructor...

**Comment by DaGhostman** [comment] 2016-09-28 20:05
Hmm.. I would guess so, since PHP4 style constructors are still deprecated (I thought they ware removed in 7, but probably not).. Strange thing is that no error/warning messages appear, as they should according to the docs: 

> PHP 7 will emit E_DEPRECATED if a PHP 4 constructor is the only constructor defined within a class.
 
This might be an issue on my side, although:
```
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);
```

are the first lines of the script, still nothing. Your recommendation seems reasonable as they are not removed, but should't they be case sensitive..?

**Comment by Ocramius** [comment] 2016-09-28 20:08
@DaGhostman php methods are not case sensitive. Does the weird behavior persist when changing method name?

**Comment by DaGhostman** [comment] 2016-09-28 20:23
Yeah appears to be the problem, strange that nothing is comming out of PHP tho, but.. yeah.
It is in fact considered as a constructor!

**Comment by Ocramius** [comment] 2016-09-28 20:28
This is still a bug: ProxyManager should at least attempt at recognizing the problem. This might also be a problem in the reflection API, if `ReflectionMethod#isConstructor()` is failing.

**Comment by DaGhostman** [comment] 2016-09-29 15:46
Might that be because the reflection API is looking only for the 5.0+ style constructors, hence making it a PHP bug? 

P.S: A workaround (ugly still..) might be to manually check `ReflectionMethod#isConstructor()` as well as `RelfectinonMethod#getName()` or `ReflectionClass#hasMethod()` in order to work around this specific issue, I cannot think of any reasonable workaround

**Comment by Ocramius** [comment] 2016-09-29 15:51
@DaGhostman they are still constructors, so this is indeed an edge case, and not a bug :-(

https://3v4l.org/mtlBg

```php
<?php

class foo
{
    public function foo()
    {
        var_dump(__METHOD__);
    }
}

var_dump((new \ReflectionMethod(foo::class, 'foo'))->isConstructor());

(new foo())->foo();
```

**Comment by Ocramius** [comment] 2020-12-20 16:31
This is to be closed once PHP 8 support is enforced, since PHP 8 finally got rid of PHP4 constructors (see same 3v4l link as before: https://3v4l.org/mtlBg)

**Comment by Ocramius** [comment] 2020-12-30 16:22
No time to get it in `2.11.0`, hence moving it to `2.12.0`

**Closed** 2021-07-13 21:58 UTC
Labels: bug
