### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by Venorcis** [Ocramius/ProxyManager#719] opened 2021-12-02 15:36 UTC
"ocramius/proxy-manager 2.13.0 requires php ~7.4.1 || ~8.0.0 -> your php version (8.1.0) does not satisfy that requirement."

**Comment by Ocramius** [comment] 2021-12-02 15:41
Duplicate of #716

**Closed as completed by Ocramius** 2021-12-02 15:41 UTC
Labels: duplicate, question

**Comment by Venorcis** [comment] 2021-12-02 15:43
> Duplicate of #716

that issue is already closed though, maybe good to keep it open so it's visible?

**Comment by Ocramius** [comment] 2021-12-02 15:45
Not really: support work still needs to start, and I know I have to do it.

Mostly involves tons of added tests and edge case scenarios around `never` and similar, for which I still need to formulate the actual tasks.

The upstream `laminas/laminas-code` work needs to be completed first anyway.
