### ISSUE TITLE
Intercept all method calls?

### ISSUE THREAD

**Issue by mnapoli** [Ocramius/ProxyManager#302] opened 2016-03-20 20:43 UTC
`AccessInterceptorInterface` only allows to intercept specific methods (`setMethodPrefixInterceptor()`  requires a method name). Is there a way to intercept all method calls to the proxy? I couldn't find anything after searching a bit, I hope I didn't miss something obvious.

**Comment by Ocramius** [comment] 2016-03-20 21:56
This is a duplicate of #236

**Closed by Ocramius** 2016-03-20 21:56 UTC

**Comment by mnapoli** [comment] 2016-03-20 22:02
:+1:
